//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practice.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnavailableDate
    {
        public int Id { get; set; }
        public string SiblingId { get; set; }
        public System.DateTime Busydate { get; set; }
    
        public virtual Sibling Sibling { get; set; }
    }
}
